# Generated by Django 3.2.7 on 2021-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviaticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('from_him', models.CharField(max_length=50)),
                ('where_him', models.CharField(max_length=50)),
                ('what', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
